version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      NODE_ENV: production

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      args:
        VITE_API_URL: http://localhost:4000/api
    ports:
      - "4173:4173"
    environment:
      VITE_API_URL: http://localhost:4000/api
    depends_on:
      - backend
